### ISSUE TITLE
能稍微解释下这样怎么能线上修复bug吗？

### ISSUE THREAD

**Issue by luyuanmogujie** [dodola/RocooFix#11]
1.因为我看demo，也是需要手动修改gradle的配置，这样怎么通过不发版来修bug呢？

2.patch文件是提前写好的吗？

**Comment by Dongzzzz** [comment]
1.发现问题，解决问题
2.修改gradle 生成patch.jar
3.将patch.jar发布到服务器。
4.客户端根据自己的修复逻辑来决定什么时候下载patch.jar，什么时候去加载patch.jar
5.patch.jar加载完成，bug被fix

**Comment by dodola** [comment]
@luyuanmogujie 同上，我更新了一下readme，之前写的方法都是从asset里加载补丁，可能对你造成了一些理解错误
