### ISSUE TITLE
程序运行提示rocoo.dex有问题

### ISSUE THREAD

**Issue by FordLiu** [dodola/RocooFix#15]
06-01 17:28:55.675 1470-1488/? D/dalvikvm: Debugger has detached; object registry had 1 entries
06-01 17:28:55.705 1470-1470/? E/dalvikvm: ERROR: unrecognized magic number (50 4b 03 04)
06-01 17:28:55.705 1470-1470/? E/dalvikvm: Error with header for /data/data/com.dodola.rocoosample/files/hotfix/rocoo.dex

**Comment by dodola** [comment]
@FordLiu 已经修复
