### ISSUE TITLE
运行Demo没有效果

### ISSUE THREAD

**Issue by wenjiang** [dodola/RocooFix#17]
一运行，就报06-01 18:08:31.770 16731-16731/com.dodola.rocoosample E/dalvikvm: Could not find class 'com.dodola.rocoo.Hack', referenced from method com.dodola.rocoosample.a.<init>

**Comment by Dongzzzz** [comment]
。。看看有没有这个 文件
![image](https://cloud.githubusercontent.com/assets/16301715/15732127/0a4137e2-28ad-11e6-9cff-9982eaedf928.png)

**Comment by wenjiang** [comment]
@Dongzzzz  是有这个文件，下载下来的例子只要一运行，就会报这个错误
06-02 10:37:09.817 2101-2101/com.dodola.rocoosample E/dalvikvm: ERROR: unrecognized magic number (50 4b 03 04)
06-02 10:37:09.817 2101-2101/com.dodola.rocoosample E/dalvikvm: Error with header for /data/data/com.dodola.rocoosample/files/hotfix/rocoo.dex

**Comment by Dongzzzz** [comment]
![image](https://cloud.githubusercontent.com/assets/16301715/15732416/7cba8164-28af-11e6-9858-0d288dbc7ee4.png)
这个就是那个dex里面的内容，如果你不理解什么意思，不知道为什么需要这个dex。https://zhuanlan.zhihu.com/p/20308548 
https://github.com/dodola/HotFix
你可以看下知乎的那个文章和HotFix的 README.md

**Comment by Dongzzzz** [comment]
而且我刚才看了下 close 的issue  貌似这个问题已经修复了，你重新去下一份看看

**Comment by dodola** [comment]
应该已经没有这个问题了
