### ISSUE TITLE
虽然生成了version目录，但里面并没有pach

### ISSUE THREAD

**Issue by 601367322** [dodola/RocooFix#18]

**Comment by wenjiang** [comment]
你例子工程跑起来有用吗？我试过，没用。。。

**Comment by 601367322** [comment]
跑起来了，找到原因，是因为我的项目加了productFlavors
希望修复此bug

**Comment by wenjiang** [comment]
@601367322 我直接跑例子都没跑起来。。。

**Comment by 601367322** [comment]
模拟器都可以了，但我的三星s4 5.0.1不行

**Comment by wenjiang** [comment]
@601367322 我华为 4.4.4，运行起来就是没反应

**Comment by dodola** [comment]
@601367322 是用的那种方式运行的补丁？

**Comment by dodola** [comment]
@601367322 productFlavors刚看了一下确实有问题

**Comment by 601367322** [comment]
@dodola 5.0.1的，应该是ART

**Comment by dodola** [comment]
@601367322 5.0的你再看看

**Comment by 336Project** [comment]
@dodola productFlavors问题什么时候可以修复呢

**Comment by dodola** [comment]
已经修复 `classpath 'com.dodola:rocoofix:1.1'`
