### ISSUE TITLE
内部类问题

### ISSUE THREAD

**Issue by Dongzzzz** [dodola/RocooFix#19]
![image](https://cloud.githubusercontent.com/assets/16301715/15704744/904a504c-281e-11e6-92d1-e168c2b7531e.png)
如上图 DemoActivity8是需要被修复的类，修复的内容是加了一个内部类TestInterfaceImpl。
生成path.jar 然后运行原apk，先在主页面运行`RocooFix.initPathFromAssetsRuntime(this, "patch.jar");`
然后启动DemoActivity8。程序崩溃
![image](https://cloud.githubusercontent.com/assets/16301715/15704856/0fe7d572-281f-11e6-907a-50cb85d9183d.png)
![image](https://cloud.githubusercontent.com/assets/16301715/15732036/589b987a-28ac-11e6-8c8c-5e928daf1dd4.png)

如果先去启动DemoActivity8， 然后退出DemoActivity8回到主页面，运行`RocooFix.initPathFromAssetsRuntime(this, "patch.jar");` ，然后再次进入DemoActivity8 则没有任何问题

**Comment by dodola** [comment]
@Dongzzzz 应该已经修复，如果还有问题，可以提供一下你的测试用例，我再看看
