### ISSUE TITLE
Error:Connection refused: connect

### ISSUE THREAD

**Issue by menghuanmusic** [dodola/RocooFix#21]
项目的根build.gradle添加
maven {
            url "http://dl.bintray.com/dodola/maven"
        }
classpath 'com.dodola:rocoofix:1.0'
之后。Sync now时，出现了Error:Connection refused: connect的错误

**Comment by Dongzzzz** [comment]
自己网的问题 试试在网页中能不能打开 http://dl.bintray.com/dodola/maven

**Comment by dodola** [comment]
@menghuanmusic 应该是你那网络环境问题，你试试翻墙看看

**Comment by menghuanmusic** [comment]
直接打开那个链接可以的。我分开往build.gradle中添加
maven {
url "http://dl.bintray.com/dodola/maven"
}
和
classpath 'com.dodola:rocoofix:1.0'

发现是在添加classpath之后，要去下载这个资源时，报的这个error的错误。

**Comment by menghuanmusic** [comment]
翻墙后，确实可以。是网络问题。
