### ISSUE TITLE
点击按钮“FIXMERUNTIME”在安卓5.0以上系统报错

### ISSUE THREAD

**Issue by nedpan** [dodola/RocooFix#23]
点击按钮“FIXMERUNTIME”，
调用方法“RocooFix.initPathFromAssetsRuntime(MainActivity.this, "patch.jar");”
在安卓系统5.0以下正常使用，但是在5.0以上报错崩溃，崩溃信息如下：

![image](https://cloud.githubusercontent.com/assets/6016479/15737115/c7ccb588-28d6-11e6-86e8-e6ad468c5306.png)

不知诸位有没有遇到同样的问题，是怎么解决的？不吝赐教。

**Comment by dodola** [comment]
@nedpan 发一下完整的 core dump 日志我分析一下，我这没有5.0手机，模拟器上是没有问题的

**Comment by nedpan** [comment]
[rocoofix_error.docx](https://github.com/dodola/RocooFix/files/295196/rocoofix_error.docx)
以上是全部日志，请查收。
补充说明下：在我的测试手机里，当点击按钮“FIXMERUNTIME”，动态修复情况如下：
5.0以下安卓手机：MX4,LenovoA360t这两款都可以正常动态修复。
5.0以上安卓手机：
三星S6[系统5.1.1]、HTC M8d[系统6.0]可以正常动态修复;
但是三星S5[系统5.0]，Vivo X5M[系统5.0.2]，华为Mate7[系统5.1]出现崩溃情况。

**Comment by nedpan** [comment]
三星S4 GT-I9500[系统5.0.1]也出现崩溃情况。

**Comment by mars-ma** [comment]
红米NOTE3 Android版本 5.0.2也出现崩溃，华为P7 Android 4.2.2没有问题

**Comment by dodola** [comment]
@mars-ma @nedpan 我这5.0的nexus已经修复，你看看你们其他的手机

**Comment by nedpan** [comment]
@dodola 哥们，还是有些问题想请教，方便的话加下我的QQ：1261329618

**Comment by nedpan** [comment]
基于安卓5.0以上的崩溃问题，您修复更新了新的版本，把“RocooFix.initPathFromAssets(this, "patch.jar");”初始化工作放在application的attachBaseContext方法来做。
那么我想问：要知道很多app退出后并没有完全杀死，当你再次打开app，发现application的attachBaseContext方法并没有再次调用。基于这种情况，动态修复补丁的快速性就打折了，如何实现更快速的动态修复？

譬如HelloHack
我在调用RocooFix.initPathFromAssets(this, "patch.jar");方法前已经使用了HelloHack，那么无论怎么调用RocooFix.initPathFromAssets(this, "patch.jar");都无法完成热修复

app在启动时，补丁包一般是从服务端下载的，当下载补丁包完毕后，我们要实现在app使用中就替换掉需要打补丁的类，这样的意义性更大。
