### ISSUE TITLE
没生成path.jar补丁

### ISSUE THREAD

**Issue by xuzixuam** [dodola/RocooFix#29]
按照demo运行没生成path.jar补丁啊！

**Comment by xuzixuam** [comment]
Executing tasks: [:app:assembleDebug]

Configuration on demand is an incubating feature.
:buildsrc:compileJava UP-TO-DATE
:buildsrc:compileGroovy UP-TO-DATE
:buildsrc:processResources UP-TO-DATE
:buildsrc:classes UP-TO-DATE
:buildsrc:jar UP-TO-DATE
:buildsrc:assemble UP-TO-DATE
:buildsrc:compileTestJava UP-TO-DATE
:buildsrc:compileTestGroovy UP-TO-DATE
:buildsrc:processTestResources UP-TO-DATE
:buildsrc:testClasses UP-TO-DATE
:buildsrc:test UP-TO-DATE
:buildsrc:check UP-TO-DATE
:buildsrc:build UP-TO-DATE
=========C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\rocoofix\version2
=========C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\rocoofix\version2\debug
=========C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\rocoofix\version2\debug\patch
=========C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\rocoofix\version2\debug\hash.txt
==========2
-------------------dexTask:task ':app:transformClassesWithDexForDebug'
-------------------rocooClassTask:task ':app:rocooJarBeforeDexDebug'
C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\rocoofix\version1\release\hash.txt does not exist
=========C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\rocoofix\version2
=========C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\rocoofix\version2\release
=========C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\rocoofix\version2\release\patch
=========C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\rocoofix\version2\release\hash.txt
==========2
-------------------dexTask:task ':app:transformClassesWithDexForRelease'
-------------------rocooClassTask:task ':app:rocooJarBeforeDexRelease'
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:rocoo:preBuild UP-TO-DATE
:rocoo:preReleaseBuild UP-TO-DATE
:rocoo:compileReleaseNdk UP-TO-DATE
:rocoo:compileLint
:rocoo:copyReleaseLint UP-TO-DATE
:rocoo:checkReleaseManifest
:rocoo:preDebugAndroidTestBuild UP-TO-DATE
:rocoo:preDebugBuild UP-TO-DATE
:rocoo:preDebugUnitTestBuild UP-TO-DATE
:rocoo:preReleaseUnitTestBuild UP-TO-DATE
:rocoo:prepareComAndroidSupportAnimatedVectorDrawable2340Library UP-TO-DATE
:rocoo:prepareComAndroidSupportAppcompatV72340Library UP-TO-DATE
:rocoo:prepareComAndroidSupportSupportV42340Library UP-TO-DATE
:rocoo:prepareComAndroidSupportSupportVectorDrawable2340Library UP-TO-DATE
:rocoo:prepareReleaseDependencies
:rocoo:compileReleaseAidl UP-TO-DATE
:rocoo:compileReleaseRenderscript UP-TO-DATE
:rocoo:generateReleaseBuildConfig UP-TO-DATE
:rocoo:generateReleaseAssets UP-TO-DATE
:rocoo:mergeReleaseAssets UP-TO-DATE
:rocoo:generateReleaseResValues UP-TO-DATE
:rocoo:generateReleaseResources UP-TO-DATE
:rocoo:mergeReleaseResources UP-TO-DATE
:rocoo:processReleaseManifest UP-TO-DATE
:rocoo:processReleaseResources UP-TO-DATE
:rocoo:generateReleaseSources UP-TO-DATE
:rocoo:compileReleaseJavaWithJavac UP-TO-DATE
:rocoo:extractReleaseAnnotations UP-TO-DATE
:rocoo:mergeReleaseProguardFiles UP-TO-DATE
:rocoo:packageReleaseRenderscript UP-TO-DATE
:rocoo:packageReleaseResources UP-TO-DATE
:rocoo:processReleaseJavaRes UP-TO-DATE
:rocoo:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:rocoo:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:rocoo:mergeReleaseJniLibFolders UP-TO-DATE
:rocoo:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:rocoo:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:rocoo:bundleRelease UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2340Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72340Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42340Library UP-TO-DATE
:app:prepareComAndroidSupportSupportVectorDrawable2340Library UP-TO-DATE
:app:prepareRocooFixMasterRocooUnspecifiedLibrary UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:transformClassesAndResourcesWithProguardForDebug
ProGuard, version 5.2.1
Reading input...
Reading program jar [E:\studioSdk\android-sdk_r24.4.1-windows\android-sdk-windows\extras\android\m2repository\com\android\support\support-annotations\23.4.0\support-annotations-23.4.0.jar] (filtered)
Reading program jar [C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.4.0\jars\classes.jar] (filtered)
Reading program jar [C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\build\intermediates\exploded-aar\com.android.support\animated-vector-drawable\23.4.0\jars\classes.jar] (filtered)
Reading program jar [C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\build\intermediates\exploded-aar\com.android.support\support-vector-drawable\23.4.0\jars\classes.jar] (filtered)
Reading program jar [C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\build\intermediates\exploded-aar\com.android.support\support-v4\23.4.0\jars\classes.jar] (filtered)
Reading program jar [C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\build\intermediates\exploded-aar\com.android.support\support-v4\23.4.0\jars\libs\internal_impl-23.4.0.jar] (filtered)
Reading program jar [C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\build\intermediates\exploded-aar\RocooFix-master\rocoo\unspecified\jars\classes.jar] (filtered)
Reading program directory [C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\build\intermediates\classes\debug] (filtered)
Reading library jar [E:\studioSdk\android-sdk_r24.4.1-windows\android-sdk-windows\platforms\android-23\android.jar]
Reading library jar [E:\studioSdk\android-sdk_r24.4.1-windows\android-sdk-windows\platforms\android-23\optional\org.apache.http.legacy.jar]
Note: duplicate definition of library class [android.net.http.SslCertificate]
Note: duplicate definition of library class [android.net.http.SslError]
Note: duplicate definition of library class [android.net.http.SslCertificate$DName]
Note: duplicate definition of library class [org.apache.http.conn.scheme.SocketFactory]
Note: duplicate definition of library class [org.apache.http.conn.scheme.HostNameResolver]
Note: duplicate definition of library class [org.apache.http.conn.ConnectTimeoutException]
Note: duplicate definition of library class [org.apache.http.params.HttpParams]

Note: there were 7 duplicate class definitions.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)

Initializing...
Note: com.dodola.rocoofix.RocooFix$V23 calls 'Field.getType'
Note: com.lody.legend.art.ArtMethod: can't find dynamically referenced class java.lang.reflect.AbstractMethod
Note: com.lody.legend.art.ArtMethod: can't find dynamically referenced class java.lang.reflect.ArtMethod
Note: com.lody.legend.utility.Runtime: can't find dynamically referenced class dalvik.system.VMRuntime
Note: com.lody.legend.utility.Runtime: can't find dynamically referenced class dalvik.system.VMRuntime
Note: com.lody.legend.art.ArtMethod accesses a declared field 'artMethod' dynamically
Note: com.lody.legend.art.ArtMethod accesses a declared field 'artMethod' dynamically
Note: there were 1 classes trying to access generic signatures using reflection.
      You should consider keeping the signature attributes
      (using '-keepattributes Signature').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#attributes)
Note: there were 4 unresolved dynamic references to classes or interfaces.
      You should check if you need to specify additional program jars.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)
Note: there were 2 accesses to class members by means of introspection.
      You should consider explicitly keeping the mentioned class members
      (using '-keep' or '-keepclassmembers').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclassmember)
Ignoring unused library classes...
  Original number of library classes: 3880
  Final number of library classes:    881
Printing kept classes, fields, and methods...
Shrinking...
Printing usage to [C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\build\outputs\mapping\debug\usage.txt]...
Removing unused program classes and class elements...
  Original number of program classes: 1577
  Final number of program classes:    688
Obfuscating...
Applying mapping [C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\rocoofix\version1\debug\mapping.txt]
Printing mapping to [C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\build\outputs\mapping\debug\mapping.txt]...
Writing output...
Preparing output jar [C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\build\intermediates\transforms\proguard\debug\jars\3\1f\main.jar]
  Copying resources from program jar [E:\studioSdk\android-sdk_r24.4.1-windows\android-sdk-windows\extras\android\m2repository\com\android\support\support-annotations\23.4.0\support-annotations-23.4.0.jar] (filtered)
  Copying resources from program jar [C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.4.0\jars\classes.jar] (filtered)
  Copying resources from program jar [C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\build\intermediates\exploded-aar\com.android.support\animated-vector-drawable\23.4.0\jars\classes.jar] (filtered)
  Copying resources from program jar [C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\build\intermediates\exploded-aar\com.android.support\support-vector-drawable\23.4.0\jars\classes.jar] (filtered)
  Copying resources from program jar [C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\build\intermediates\exploded-aar\com.android.support\support-v4\23.4.0\jars\classes.jar] (filtered)
  Copying resources from program jar [C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\build\intermediates\exploded-aar\com.android.support\support-v4\23.4.0\jars\libs\internal_impl-23.4.0.jar] (filtered)
  Copying resources from program jar [C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\build\intermediates\exploded-aar\RocooFix-master\rocoo\unspecified\jars\classes.jar] (filtered)
  Copying resources from program directory [C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\build\intermediates\classes\debug] (filtered)
Printing classes to [C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\build\outputs\mapping\debug\dump.txt]...
:app:rocooJarBeforeDexDebug
-------------------proguardTask:task ':app:transformClassesAndResourcesWithProguardForDebug'
-------------------mapFile:C:\Users\Administrator\Desktop\RocooFix-master-old\RocooFix-master\app\build\outputs\mapping\debug\mapping.txt
-------------------copy mapping file:
:app:applyRocooDebugPatch
==============applyRocooDebugPatch
:app:transformClassesWithDexForDebug
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:app:validateDebugSigning
:app:packageDebug
:app:zipalignDebug
:app:assembleDebug

BUILD SUCCESSFUL

Total time: 8.923 secs


这是我的Gradle 日志，@dodola 麻烦看看

**Comment by xuzixuam** [comment]
我用的手机是小米note，Android版本5.0.2 麻烦解决下  @dodola

**Comment by dodola** [comment]
@xuzixuam 如果上一个版本没有开启混淆，那么制作补丁的后一个版本也不能开启混淆

**Comment by xuzixuam** [comment]
@dodola都试过了。都不开启混淆的情况也不行。

**Comment by daixiansen** [comment]
我也遇到了同样的问题.

**Comment by zhlo1012** [comment]
includePackage 记得改成你自己的包名

**Comment by daixiansen** [comment]
@zhlo1012 改包名 啥意思?

**Comment by LunYing** [comment]
@dodola 在linux系统编译可以生成patch.jar ，在win下生成不了

**Comment by dodola** [comment]
@LunYing  win 下打包失败情况应该已经解决
