### ISSUE TITLE
找不RocooFix

### ISSUE THREAD

**Issue by hsoftxl** [dodola/RocooFix#31]
根据说明进行配置后， 提示找不到Rocoofix

**Comment by joure** [comment]
需要依赖 rocoo 这个module

**Comment by MyLifeMyTravel** [comment]
依赖rocoo这个module也不一定能生成patch.jar

**Comment by joure** [comment]
@MyLifeMyTravel  我直接用 Demo 没问题，但是单独引入 launch 的时候一直 crash, 找不到Hack类

**Comment by xuzixuam** [comment]
@MyLifeMyTravel 根本生成不了patch.jar

**Comment by fengnudexiaoniao** [comment]
@joure 那是因为你的application继承了别的父类application，需要把这个父类排除掉，可以加入561394234群交流
