### ISSUE TITLE
没生成path.jar补丁

### ISSUE THREAD

**Issue by 505239375** [dodola/RocooFix#33]
只生成了hash,txt ，其他的都没有生成，请问这个怎么处理啊。目前这个是不是还在优化中，还不是很稳定。

**Comment by dodola** [comment]
@505239375 我基本上还没有遇到过这种情况，其他我身边的同学使用的时候也没有遇到过这种情况，还是有可能出现在混淆的情况上，上一个版本打开混淆时生成hash。txt生成补丁的那个版本也需要打开混淆才能生成补丁，相对的，如果一直都是无混淆状态，那么生成补丁的时候也是需要是关闭混淆的状态，还有就是这个暂时不支持productFlavors
