### ISSUE TITLE
patch.jar问题

### ISSUE THREAD

**Issue by 331770916** [dodola/RocooFix#34]
我看了提问题都是patch.jar没有生成， 我也试了好多次， 作者大人能解答一下吗？

**Comment by dodola** [comment]
@331770916 怀疑是混淆造成的，如果上一次生成hash的时候没有打开混淆，那么制作补丁的那个版本也不能开启混淆，如果最初就是开启混淆的，那么以后的所有版本都要开启混淆才会成功。

**Comment by dodola** [comment]
@331770916 我修改了一下，将         
classpath 'com.dodola:rocoofix:1.0' 改为        classpath 'com.dodola:rocoofix:1.1'
看看还有没有这个问题

**Comment by 331770916** [comment]
谢谢楼主大人
