### ISSUE TITLE
6.0.1中不能用

### ISSUE THREAD

**Issue by zhong1990** [dodola/RocooFix#36]
混淆签名后在4.4中可以 在6.0.1中就不行了 有遇到相同问题的吗  怎么解决呀 我用的是nexus5

**Comment by dodola** [comment]
我用nexus6测试没有这种情况呀，是不是你用的没有混淆的补丁

**Comment by zhong1990** [comment]
用的也是混淆的补丁  在4.4.4中可以正常使用  debug版本在4.4.4和6.0.1中都可以正常使用

**Comment by aaapei** [comment]
lz后面解决了吗，遇到相同问题了

**Comment by dodola** [comment]
@zhong1990 @aaapei 我增加了一种针对 ART 的打包方式，有个开关叫 scanref 请在文档中找一下这个，帮我测试一下
