### ISSUE TITLE
作者有没有可能把插件发布到mavenCentral或者jcenter上？

### ISSUE THREAD

**Issue by Drizzlezhang** [dodola/RocooFix#37]
如题

**Comment by dodola** [comment]
Gradle的插件现在上传到我自己的maven库里了，我看看发布到jcenter上。
            url "http://dl.bintray.com/dodola/maven"

**Comment by Drizzlezhang** [comment]
对，我看到在你自己的maven库里了，看作者同学啥时候方便啦
