### ISSUE TITLE
作者你好：我在魅族5手机上使用静态加载的demo重启没有生效是什么原因，能否帮忙解决下

### ISSUE THREAD

**Issue by 710224800** [dodola/RocooFix#39]
作者你好：我在魅族5手机上使用静态加载的demo重启没有生效是什么原因，能否帮忙解决下

**Comment by dodola** [comment]
@710224800 额，我这没有魅族5的手机，不太好解决，一般情况下支持multidex的手机应该不会有问题呀

**Comment by 710224800** [comment]
找到原因了，是因为混淆的，安装手机上的apk没有混淆，但是打的包是混淆的，所以可能是没有找到方法

**Comment by 710224800** [comment]
但是我在另一台手机上运行demo报这个错：06-14 10:04:18.951 22434-22434/com.dodola.rocoosample.runtimefix E/Rocoo: replaceMethod
                                                                          java.lang.IllegalStateException: Cannot create backup method from :: public java.lang.String com.dodola.rocoosample.HelloHack.showHello()
