### ISSUE TITLE
生成patch.jar之后怎么更新线上版本啊？

### ISSUE THREAD

**Issue by 69android69** [dodola/RocooFix#4]

**Comment by dodola** [comment]
@69android69 这个就是需要自己去处理这个逻辑了，你可以自定义补丁信息，把它下载到一个固定的目录，然后启动的时候循环遍历，这部分我没有做处理，如果有需要的话我可以补上一个extension 项目

**Comment by 69android69** [comment]
@dodola 啊 知道了，不用麻烦了，我先试一试。
