### ISSUE TITLE
运行报错TransformException

### ISSUE THREAD

**Issue by FordLiu** [dodola/RocooFix#40]
com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Translation has been interrupted

根据网上的说法也设置了 multiDexEnabled true但是也不好使

**Comment by dodola** [comment]
@FordLiu 是不是开了Instant run了，我这个插件跟Instantrun有点冲突。。。

**Comment by FordLiu** [comment]
我现在的as是1.5版本没有开启instant run的权限

**Comment by dodola** [comment]
@FordLiu 查了一下这个问题你试着升级一下到2.0看看好使不

**Comment by FordLiu** [comment]
是让我的as版本升级到2.0吗

**Comment by FordLiu** [comment]
我升级到as到2.1，gradle使用的也是2.1也不行

**Comment by xuanfengwuxiang** [comment]
我也遇到这个问题了，请问怎么解决啊？一直没找到方法
