### ISSUE TITLE
能生成patch.jar  但是内部没有任何修改内容的标记 

### ISSUE THREAD

**Issue by 13718325203** [dodola/RocooFix#44]
我的项目现在能生成 patch.jar  文件了！但是呢，patch.jar 里面的文件都没有内容；我现在是修改  类  HelloHack.java  文件的内容，然后就生成不了 patch.jar了！这..........我都搞了一个星期了，请问作者你能测通吗！帮忙解决一下，谢谢

**Comment by dodola** [comment]
@13718325203 能把你的项目发到我邮箱么 dinophp@gmail.com，我运行看一下是什么问题造成的
