### ISSUE TITLE
这样可以不让注入hack那段代码执行,就可以杜绝有些加载早的类找不到hack

### ISSUE THREAD

**Issue by sukeygithub** [dodola/RocooFix#45]
https://github.com/Livyli/AndHotFix/blob/master/buildSrc/src/main/groovy/cn/jiajixin/nuwa/util/NuwaProcessor.groovy

**Comment by dodola** [comment]
@sukeygithub 嗯，我也发现InstantRun 会造成找不到 Hack 的类情况

**Comment by sukeygithub** [comment]
链接中那NuwaProcessor.groovy是改造过的，前面加入了if(false) ，这样Hack在运行时就不会执行，不会找不到了

**Comment by 13718325203** [comment]
你们说的 文件  我都找不到是在哪儿啊！你们是跑的 RocooFix  项目吗

**Comment by dodola** [comment]
@sukeygithub @13718325203 这个应该不会再出现这个问题

**Comment by dodola** [comment]
@sukeygithub @13718325203 请获取最新代码
