### ISSUE TITLE
关于打上CLASS_ISPREVERIFIED标志。

### ISSUE THREAD

**Issue by hunanqi** [dodola/RocooFix#47]
你好，经过测试已经完成修复，就是有一点，关于打上CLASS_ISPREVERIFIED标志这种事，看了原理，需要向每个类中注入一段应用其它dex文件中类的代码。可是测试后反编译并没有看到有注入代码。我想问问这是什么原因呢？还有就是您的源码中buidsrc模块应该就是做这个事的，但是似乎集成的时候并没有用到。反编译也没有看到效果

**Comment by dodola** [comment]
@hunanqi CLASS_ISPREVERIFIED这个标记是Dalvik虚拟机在加载类的时候才会加进去的，具体可以看这段代码 http://androidxref.com/4.4.4_r1/xref/dalvik/vm/oo/Resolve.cpp#118
