### ISSUE TITLE
ButterKnife引入后产生错误

### ISSUE THREAD

**Issue by jiantao88** [dodola/RocooFix#54]
错误: 服务配置文件不正确, 或构造处理程序对象javax.annotation.processing.Processor: Provider butterknife.internal.ButterKnifeProcessor could not be instantiated: java.lang.NoClassDefFoundError: com/dodola/rocoo/Hack时抛出异常错误
:app:compileDebugJavaWithJavac FAILED
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by dodola** [comment]
@jiantao88 这个问题已经修复

**Comment by legendmohe** [comment]
请问是如何修复的？这个问题产生的原因是什么？

**Comment by David-Kuper** [comment]
请问这个问题怎么修复的？我的配置代码已经通过编译，但是执行的时候就报这个错误。能告诉我怎么解决嘛？
`
APPLevel（build.gradle）
apply plugin: 'android-apt'
 
compile 'com.jakewharton:butterknife:8.0.1'
    apt 'com.jakewharton:butterknife-compiler:8.0.1'

ProjectLevel(build.gradle)

dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.0.1'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
`
