### ISSUE TITLE
Error:Execution failed for task ':app:rocooJarBeforeDexDebug'. > Unexpected internal error near index 6   debug\         ^

### ISSUE THREAD

**Issue by lllxhxsh** [dodola/RocooFix#75]
在编译apk的时候出现错误

Error:Execution failed for task ':app:rocooJarBeforeDexDebug'.
> Unexpected internal error near index 6
  debug\
        ^

**Comment by shoyu666** [comment]
@lllxhxsh  com.android.tools.build:gradle:2.1.2
如果还不行  加入--strack... 输出详细错误

**Comment by dodola** [comment]
@lllxhxsh 已经修复这个问题了哈
