### ISSUE TITLE
scanref为什么要去寻找继承？

### ISSUE THREAD

**Issue by Dongzzzz** [dodola/RocooFix#83]
scanref为什么要去找继承关系？有的类直接找到的java.lang.Object类，这种系统类加入进去有什么存在的意义么？主要不太理解的是为什么把继承的关系加入进去?不是直接寻找引用关系就可以了么？
@shoyu666  @dodola

**Comment by shoyu666** [comment]
@Dongzzzz  根据微信的文章 上面说 所以修改了类变量和方法的类的父类和引用了该类的类
另外java.lang.Object并不会加入补丁，任何不在jar包里面的类都不可能加入补丁

**Comment by Dongzzzz** [comment]
![image](https://cloud.githubusercontent.com/assets/16301715/17430723/91516f24-5b28-11e6-8507-d33cb2e0de6f.png)
![image](https://cloud.githubusercontent.com/assets/16301715/17430746/a41104e4-5b28-11e6-9cab-e6f4e4c9f8c1.png)


我看这里没有进行判断过滤不在jar包里面的类

**Comment by shoyu666** [comment]
@Dongzzzz   这里是没有判断 但是在写入补丁的时候  Object.class是找不到的，所以不会存在写入Object.class
