### ISSUE TITLE
为什么我总是构建不起来，是要配置groovySDK么

### ISSUE THREAD

**Issue by blackk22** [dodola/RocooFix#9]
----------------------------问题一----------------------------------------------
Error:(21, 0) No such property: includePackage for class: com.dodola.rocoofix.RocooFixExtension_Decorated <a href="openFile:D:\Rocoo\app\build.gradle">Open File</a>

----------------------------问题二--------------------------------------
Error:Gradle: Execution failed for task ':mshop:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_71\bin\java.exe'' finished with non-zero exit value2

构建的时候总是有各种问题，我们的项目结构是一个A library module依赖 B library module ,B再依赖app这个module。 而且项目中用到的jar包是放在libs里面的，不是compile xxx方式。构建的时候总是出问题。

**Comment by dodola** [comment]
@blackk22 Sorry my fault,already fixed
