### ISSUE TITLE
apply plugin: 'com.dodola.rocoofix'  编译过不去

### ISSUE THREAD

**Issue by dazhiyu** [dodola/RocooFix#98]
报  Error:(2, 0) Cause: com/dodola/rocoofix/RocooFixPlugin : Unsupported major.minor version 52.0
<a href="openFile:E:\huajuan\trunk\app\build.gradle">Open File</a>

**Comment by msilemsile** [comment]
复制下面的覆盖一下:

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.3'
        classpath 'com.dodola:rocoofix:1.2.6'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by dazhiyu** [comment]
不行啊，还是报这个错：
Error:(2, 0) Cause: com/dodola/rocoofix/RocooFixPlugin : Unsupported major.minor version 52.0
<a href="openFile:E:\huajuan\trunk\app\build.gradle">Open File</a>

**Comment by dazhiyu** [comment]
好像是说必须是jdk1.8。1.7不行吗

**Comment by dazhiyu** [comment]
。。。

**Comment by aliucq** [comment]
调研的时候jdk1.7还支持，昨晚调研报告就需要jdk1.8了
